sudo: required
services:
  - docker

before_install:
  - docker build -t datadiskpfv/react-test -f ./client/Dockerfile.dev ./client

script:
  # added -e CI=true to docker command to automatically exit after running npm test
  - docker run -e CI=true datadiskpfv/react-test npm run test -- --coverage

after_success:
  - docker build -t datadiskpfv/multi-client ./client
  - docker build -t datadiskpfv/multi-nginx  ./nginx
  - docker build -t datadiskpfv/multi-server ./server
  - docker build -t datadiskpfv/multi-worker ./worker

  # Push images to Docker Hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push datadiskpfv/multi-client
  - docker push datadiskpfv/multi-nginx
  - docker push datadiskpfv/multi-server
  - docker push datadiskpfv/multi-worker

deploy:
  provider: elasticbeanstalk
  region: eu-west-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-eu-west-2-052343686396
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY

